default_install_hook_types: [commit-msg, pre-commit, pre-push]
default_stages:
  - "pre-commit"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        stages: [pre-commit, pre-push]
        args: ["detect", "--redact", "-v"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        stages: [pre-commit, pre-push]
        args: ["--disable-plugin", "KeywordDetector", "--exclude-files", "dot_config/nvim/lazy-lock.json"]
